### ISSUE TITLE
Reduce COFOG/GFSM requirement

### ISSUE THREAD

**Issue by trickvi** [openspending/budget-data-package#10]
Requiring COFOG is likely to slow the adoption of the specification. A lot of countries have already put in place a different functional classification tailored to that country.

It has been proposed to move COFOG into a recommended field, not required.
Instead we can functional classification and perhaps a mapping of how that classification can be mapped to COFOG.

The same applies to GFSM and economic classifications.

**Comment by rgrp** [comment]
FIXED. At the moment no COFOG in there and even where we introduce content in #34 we will likely keep this less strict.
