### ISSUE TITLE
Hierarchical links between budget items

### ISSUE THREAD

**Issue by nmashton** [openspending/budget-data-package#11]
Sarah Bird from Open Contracting pointed out that budget data won't necessarily always be published at the most granular possible level and that it would be advantageous to be able to link budget items in a hierarchy. She proposed adding a `parent_item` ID field in order to make this possible.

**Comment by rgrp** [comment]
With the current "mapping" model this is less directly relevant though it could arise. at the moment i propose to close as wontfix / invalid and we can reopen if appropriate.
