### ISSUE TITLE
Versioning of information

### ISSUE THREAD

**Issue by trickvi** [openspending/budget-data-package#18]
Gisele Craveiro has pointed out that sometimes mappings change, for instance a local functional classification mapping to COFOG might get changed between years. The specification should have a way of dealing with such versioning of data and possibly updates.

**Comment by rgrp** [comment]
WONTFIX.

The classic way to deal with this in OLAP or similar is that you have the codes in a separate file and the key into the file contains both year and code. I don't think the spec needs to have this specifically addressed - though perhaps there could be an example. Right now will close as WONTFIX and reopen as appropriate.
